### ISSUE TITLE
Python2 support

### ISSUE THREAD

**Issue by michalgarcarz** [CiscoSecurity/tr-04-get-dispositions#1]
Hello Team,
Thanks for the script, it's working fine for python3, on python2 machine i got:

`MGARCARZ-M-J0S5:tr-04-get-dispositions# python get_dispositions.py 630325cac09ac3fab908f903e3b00d0dadd5fdaa0875ed8496fcbb97a558d0da
Traceback (most recent call last):
  File "get_dispositions.py", line 129, in <module>
    main()
  File "get_dispositions.py", line 112, in main
    response = query(observable)
  File "get_dispositions.py", line 99, in query
    response = check_auth(inspect, observable)
  File "get_dispositions.py", line 88, in check_auth
    response = function(param)
  File "get_dispositions.py", line 50, in inspect
    access_token = get_token()
  File "get_dispositions.py", line 40, in get_token
    except FileNotFoundError:
NameError: global name 'FileNotFoundError' is not defined`

And had to use the fix:
`try:
    FileNotFoundError
except NameError:
    FileNotFoundError = IOError`

Another CTR script: 01_deliberate_observables.py working fine for both python2 and python3.

**Comment by maugertg** [comment]
As of January 1, 2020 Python 2.7 will no longer be supported. With that in mind all scripts are written in Python 3; the target is Python 3.5.2 or earlier. As support for Python 3 grows over time, the target will likely change so that things like [f-strings](https://www.python.org/dev/peps/pep-0498/) can be used.

The FileNotFoundError is a more descriptive and explicit exception than IOError from Python2, which is why it was chosen. Many of the scripts here do not contain anything that is specific to Python3 which provides for Python2 compatibility.  This is much less likely in the 04 and 05 scripts than the 01 through 03 scripts.
